services:
  - type: web
    name: deadman-hiscores
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: true
      - key: SCRAPE_INTERVAL
        value: 900
    disk:
      name: database-storage
      mountPath: /opt/render/project/data
      sizeGB: 1 